# Set to true if you want to add custom CSS and include it from assets/css/custom.css
customCss = false
# Set to true if you want to add custom Js and include it from assets/js/custom.js
customJs = true
# Add a brief description for SEO purposes
description = 'Site Description'
# Specify the author's name
author = "Armoghan-ul-Mohmin"
# Provide the GitHub profile link
github = "https://github.com/Armoghan-ul-Mohmin"
# Provide the Facebook profile link
facebook = "https://facebook.com/Armoghan-ul-Mohmin"
# Specify the default Open Graph image
og_image = "/images/og.png"
# Provide the Twitter handle for the site
twitter = "@Armoghan16"
# Set to true if you want to display a copyright notice in the footer
showCopyright = true
# Set to true if you want to include a footer menu
footermenu = true
